IF DATABASE_PRINCIPAL_ID(N'chris-test-func') IS NULL
    CREATE USER [chris-test-func]
    FROM EXTERNAL PROVIDER
    WITH OBJECT_ID = '<FUNCTION_IDENTITY_OBJECT_ID>';

GRANT SELECT, INSERT, UPDATE, DELETE
    ON SCHEMA::dbo TO [chris-test-func];